romania_map = {
    'Arad': [('Zerind', 75), ('Sibiu', 140), ('Timisoara', 118)],
    'Zerind': [('Oradea', 71), ('Arad', 75)],
    'Oradea': [('Zerind', 71), ('Sibiu', 151)],
    'Sibiu': [('Arad', 140), ('Oradea', 151), ('Fagaras', 99), ('Rimnicu Vilcea', 80)],
    'Timisoara': [('Arad', 118), ('Lugoj', 111)],
    'Lugoj': [('Timisoara', 111), ('Mehadia', 70)],
    'Mehadia': [('Lugoj', 70),('Drobeta' ,75 )],
    'Drobeta':[('Craiova', 120 ),('Mehadia' ,75 )],
    'Craiova':[('Drobeta', 120), ('Rimnicu Vilcea', 146), ('Pitesti', 138)],
    'Rimnicu Vilcea':[('Sibiu', 80), ('Pitesti', 97), ('Craiova', 146)],
    'Pitesti':[('Craiova', 138), ('Rimnicu Vilcea', 97), ('Bucarest', 101)],
    'Bucarest':[('Pitesti', 101), ('Giurgiu', 90), ('Fagaras', 211), ('Urziceni', 85)],
    'Giurgiu':[('Bucarest', 90)],
    'Fagaras':[('Sibiu', 99), ('Bucarest', 211)],
    'Urziceni':[('Bucarest', 85), ('Vaslui', 142), ('Hirsova', 98)],
    'Hirsova':[('Urziceni', 98), ('Eforie', 86)],
    'Eforie':[('Hirsova', 86)],
    'Vaslui':[('Urziceni', 142), ('Iasi', 92)],
    'Iasi':[('Vaslui', 92), ('Neamt', 87)],
    'Neamt':[('Iasi', 87)]
}